CREATE TABLE IF NOT EXISTS PURCHASE_ORDER (
    UUID uuid PRIMARY KEY,
    WALLET_ID uuid NOT NULL,
    COIN VARCHAR(50)  NOT NULL,
    QUANTITY NUMERIC NOT NULL DEFAULT 0,
    PURCHASE_VALUE NUMERIC NOT NULL DEFAULT 0,
    PURCHASE_DATE TIMESTAMP WITH TIME ZONE NOT NULL
)