version: '3.9'
services:
  db:
    container_name: database
    image: postgres:13.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=start-project
      - POSTGRES_PASSWORD=start-project
      - POSTGRES_DB=start-project
    volumes:
      - postgres_start:/var/lib/postgresql/data

volumes:
  postgres_start: